# Generated by Django 3.2.6 on 2021-08-06 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testersapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='questions',
            new_name='questionsAndAnswers',
        ),
    ]
