# Generated by Django 3.2.6 on 2021-08-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testersapp', '0003_test_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='answers',
            field=models.CharField(default='0', max_length=1000),
        ),
    ]
